import os
import shutil
import re

PLOTS_DIR = '../plots'
VISUALIZE_SCORES_DIR = os.path.join(PLOTS_DIR, 'visualize_scores')
os.makedirs(VISUALIZE_SCORES_DIR, exist_ok=True)

def move_visualize_scores():
    for fname in os.listdir(PLOTS_DIR):
        fpath = os.path.join(PLOTS_DIR, fname)
        if not os.path.isfile(fpath):
            continue
        # Move files generated by visualize_scores.py (e.g., cme_<num>_composite_score.png)
        if re.match(r'cme_\d+_composite_score\\.png$', fname) or re.match(r'cme_\d+_composite_score\.png$', fname):
            shutil.move(fpath, os.path.join(VISUALIZE_SCORES_DIR, fname))

if __name__ == '__main__':
    move_visualize_scores()
    print('✅ All visualize_scores.py plots moved to their folder.')
